### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException

### ISSUE THREAD

**Issue by Sam-Levene** [mmyers/eug#25]
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

C:\Users\Sam\Downloads\Clausewitz Scenario Editor>java -Xmx512m -jar EU3_Scenario_Editor.jar
Jun 21, 2019 7:27:08 AM editor.Main main
INFO: Java version: 10.0.2
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at editor.Main.main(Main.java:66)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

C:\Users\Sam\Downloads\Clausewitz Scenario Editor>pause
Press any key to continue . . .

**Comment by mmyers** [comment]
JAXB is no longer in Java 10. Fixed in d2b163c.
