### ISSUE TITLE
Unknown source

### ISSUE THREAD

**Issue by Swacul** [mmyers/eug#33]
Nov 06, 2021 1:44:34 PM editor.Main main
INFO: Java version: 1.8.0_311
Nov 06, 2021 1:44:34 PM editor.Main main
INFO: Editor version: 0.9.7
Nov 06, 2021 1:44:47 PM editor.Main$4 actionPerformed
INFO: **************************************************
Nov 06, 2021 1:44:47 PM editor.Main lambda$main$0
SEVERE: Uncaught exception
java.lang.NullPointerException
	at editor.Main$4.actionPerformed(Main.java:268)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by mmyers** [comment]
What game and mod? It looks like the mod doesn't have a name, or at least has it defined in a way the editor doesn't expect.

**Comment by Swacul** [comment]
I tried in victoria 2 and EU 4, no mods just vanilla and copying the game directory in the correct box. wanted to do that first to test it out, but unfortunately i get this log

**Comment by mmyers** [comment]
I'm away from my computer right now so I can't test, but I believe the first time you select a new game after a clean install of the editor, you need to manually select "None" in the mod dropdown. The next time it will happen automatically. Can you try that?

**Comment by Swacul** [comment]
In the mod dropdown it shows nothing. This is from an install that i downloaded today and is the latest version.  
![image](https://user-images.githubusercontent.com/93825907/140631169-eab9b0d4-594e-48f7-871d-0b19a41a7a79.png)

**Comment by mmyers** [comment]
Is there still nothing even after you set the game directory?

**Comment by Swacul** [comment]
Wait I fixed it, seems the problem was I needed to browse the directory in your program itself instead of only copy pasting the path to the directory like i normally did.
